site_name: ChemML Documentation
site_description: Quantum-Enhanced Molecular Machine Learning Framework
site_url: https://chemml.io

theme:
  name: material
  palette:
    primary: blue
    accent: orange

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Basic Tutorial: getting-started/basic-tutorial.md
  - User Guide: USER_GUIDE.md
  - API Reference: REFERENCE.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
