version: '3.8'

services:
  # Development environment
  qemlflow-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - qemlflow-cache:/home/qemlflow/.cache
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: bash
    stdin_open: true
    tty: true

  # Jupyter notebook server
  qemlflow-notebook:
    build:
      context: .
      target: notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - qemlflow-notebook-cache:/home/qemlflow/.cache
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=qemlflow
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=qemlflow

  # Production environment
  qemlflow-prod:
    build:
      context: .
      target: production
    environment:
      - PYTHONPATH=/app
    command: python -c "import src; print('QeMLflow ready for production use')"

  # Testing environment
  qemlflow-test:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - qemlflow-test-cache:/home/qemlflow/.cache
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: pytest tests/ -v
    depends_on:
      - qemlflow-dev

  # Documentation server
  qemlflow-docs:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/app/docs
      - qemlflow-docs-cache:/home/qemlflow/.cache
    working_dir: /app
    command: mkdocs serve --dev-addr=0.0.0.0:8000

volumes:
  qemlflow-cache:
  qemlflow-notebook-cache:
  qemlflow-test-cache:
  qemlflow-docs-cache:

networks:
  default:
    name: qemlflow-network
