site_name: ChemML Documentation
site_description: Quantum-Enhanced Molecular Machine Learning Framework
site_author: ChemML Contributors
site_url: https://sanjeevardodlapati.github.io/ChemML/

repo_name: SanjeevaRDodlapati/ChemML
repo_url: https://github.com/SanjeevaRDodlapati/ChemML

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Basic Tutorial: getting-started/basic-tutorial.md
  - User Guide:
    - Overview: user-guide/overview.md
  - Development:
    - Contributing: CONTRIBUTING.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SanjeevaRDodlapati/ChemML
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/chemml/
