site_name: QeMLflow Documentation
site_description: Quantum-Enhanced Molecular Machine Learning Framework
site_url: https://qemlflow.io

theme:
  name: material
  palette:
    primary: blue
    accent: orange

nav:
  - Home: index.md
  - Getting Started: QUICK_START.md
  - User Guide: USER_GUIDE.md
  - API Reference: REFERENCE.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
