name: Automated Monitoring

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'scripts/monitoring/**'
      - '.github/workflows/monitoring.yml'

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create logs directory
      run: mkdir -p logs

    - name: Run Monitoring System
      id: monitor
      run: |
        python scripts/monitoring/automated_monitor.py
      continue-on-error: true

    - name: Upload monitoring results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: monitoring-results
        path: logs/monitoring_*.json
        retention-days: 30

    - name: Create Issue on Critical Failure
      if: steps.monitor.outcome == 'failure'
      uses: actions/github-script@v6
      with:
        script: |
          const title = '🚨 ChemML System Monitoring Alert - Critical Issues Detected';
          const body = `## Automated Monitoring Alert

          **Status**: Critical issues detected during automated monitoring
          **Timestamp**: ${new Date().toISOString()}
          **Workflow**: ${{ github.workflow }}
          **Run**: ${{ github.run_id }}

          ### Issues Detected
          The automated monitoring system has detected critical issues with the ChemML infrastructure.

          ### Quick Links
          - [GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions)
          - [Documentation Site](https://sanjeevardodlapati.github.io/ChemML/)
          - [Monitoring Results](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          ### Next Steps
          1. Check the monitoring results artifact
          2. Review failed GitHub Actions workflows
          3. Verify documentation site deployment
          4. Address any workflow or deployment issues

          ---
          *This issue was automatically created by the ChemML monitoring system.*`;

          // Check if issue already exists
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'monitoring,automated'
          });

          const existingIssue = issues.data.find(issue =>
            issue.title.includes('ChemML System Monitoring Alert')
          );

          if (!existingIssue) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['monitoring', 'automated', 'critical']
            });
          }

    - name: Comment on Success
      if: steps.monitor.outcome == 'success'
      run: |
        echo "✅ All systems operational! Monitoring completed successfully."
        echo "📊 Check the monitoring results artifact for detailed information."
