name: Automated Monitoring

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'scripts/monitoring/**'
      - '.github/workflows/monitoring.yml'

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create logs directory
      run: mkdir -p logs

    - name: Run Monitoring System
      id: monitor
      run: |
        python scripts/monitoring/automated_monitor.py
      continue-on-error: true

    - name: Upload monitoring results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: monitoring-results
        path: logs/monitoring_*.json
        retention-days: 30

    # - name: Create Issue on Critical Failure
    #   if: steps.monitor.outcome == 'failure'
    #   uses: actions/github-script@v6
    #   with:
    #     script: |
    #       # Issue creation disabled due to permissions
    #       console.log('Would create monitoring issue, but permissions not available')

    - name: Log Critical Failure
      if: steps.monitor.outcome == 'failure'
      run: |
        echo "🚨 CRITICAL: Monitoring detected issues!"
        echo "📋 Check the monitoring results artifact for details"
        echo "🔗 Manual review required at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    - name: Comment on Success
      if: steps.monitor.outcome == 'success'
      run: |
        echo "✅ All systems operational! Monitoring completed successfully."
        echo "📊 Check the monitoring results artifact for detailed information."
