name: Simple Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  basic-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test basic commands
      run: |
        echo "✅ Checkout successful"
        pwd
        ls -la
        echo "Repository contents verified"

    - name: Test Python
      run: |
        python3 --version
        python3 -c "print('✅ Python is working')"

    - name: Test environment
      run: |
        echo "Environment variables:"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "✅ Environment test completed"

    - name: Verify project structure
      run: |
        echo "Checking project structure..."
        if [ -f "README.md" ]; then
          echo "✅ README.md found"
        fi
        if [ -f ".config/mkdocs.yml" ]; then
          echo "✅ mkdocs.yml found"
        fi
        if [ -d "docs" ]; then
          echo "✅ docs/ directory found"
        fi
        if [ -d "src" ]; then
          echo "✅ src/ directory found"
        fi
        echo "✅ Project structure verification completed"
