name: Super Simple Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-simple:
    runs-on: ubuntu-latest
    name: Super Simple Test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Basic test without artifacts
      run: |
        python -c "print('✅ Super simple test passed')"
        python -c "import sys; print(f'Python version: {sys.version}')"
        echo "✅ All basic checks completed successfully!"
